@entryPoint = http://localhost:4100

#------------------------HOME 
GET {{entryPoint}}

# ----------------------------LIST
###
GET {{entryPoint}}/lists

###
POST {{entryPoint}}/lists
#format json
Content-type: application/json

{
    "title": "Fredo",
    "user_id": 1
}

#format urlencoded
# Content-type: application/x-www-form-urlencoded

# title=sample
# &order=3
# &user_id=1

###
GET {{entryPoint}}/lists/7

###
PATCH {{entryPoint}}/lists/5
#format json
Content-type: application/json
#Très strict le format d'écriture pour le test, C majuscule, espace avant application et saut à la ligne

{
    "order": 5,
    "user_id": 1
}

###
DELETE  {{entryPoint}}/lists/5

# ---------------------------- TAG
###
GET {{entryPoint}}/tags

###
POST {{entryPoint}}/tags
Content-type: application/json

{
    "name": "Gtn Color"
}

###
GET {{entryPoint}}/tags/1

###
PATCH {{entryPoint}}/tags/16
Content-type: application/json

{
    "name": "Fredo Color"
}

###
DELETE  {{entryPoint}}/tags/15

###
PUT {{entryPoint}}/cards/1/tags/autre

###
PUT {{entryPoint}}/cards/1/tags/13

###
DELETE {{entryPoint}}/cards/1/tags/13

###
GET {{entryPoint}}/cards/1/tags

# ------------------------------ CARD

###
GET {{entryPoint}}/cards
###
POST {{entryPoint}}/cards
Content-type: application/json

{
    "title": "Test 20 create",
    "order": 2,
    "description":"Lipalenonsix",
    "color":"#000",
    "user_id":1,
    "list_id":2
}
###
GET {{entryPoint}}/cards/1
###
PATCH  {{entryPoint}}/cards/13
Content-type: application/json

{
    "title": "Change test 1 / id 1",
    "order": 1,
    "description": "Test patch",
    "color": "#70c2b4",
    "list_id": 2
}
###
DELETE {{entryPoint}}/cards/15

###
GET {{entryPoint}}/lists/1/cards

###
GET {{entryPoint}}/cards/9/tags

# ----------------------------- USER


###
GET {{entryPoint}}/users/profile/6

###
POST {{entryPoint}}/users/signin
Content-type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

###
POST {{entryPoint}}/users/signup
Content-type: application/json

{
    "email": "d@d.com",
    "password": "d",
    "passwordConfirm": "d"
}

###
PATCH {{entryPoint}}/users/profile/5
Content-type: application/json

{  
    "lastname":"admin",
    "email":"admin@admin.com"
}

###
DELETE {{entryPoint}}/users/profile/6
